import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { AppProviders } from './providers'
import { ToastContainer } from 'react-toastify'
import { Montserrat } from 'next/font/google'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const montserrat = Montserrat({
	subsets: ['latin', 'cyrillic'], // если нужен кириллица — оставь cyrillic
	weight: ['400', '500', '600', '700'], // выбери нужные веса
	variable: '--font-montserrat', // удобно для tailwind/css
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${montserrat.variable} antialiased`}
			>
				<AppProviders>{children}</AppProviders>
				<ToastContainer />
			</body>
		</html>
	)
}
